import { borderWidth, colors, fontFamily, letterSpacing, minBodyFontSize, opacity, radius } from '@huddle/ui';
import { StyleSheet } from 'react-native';

const PRESS_TRAVEL = 2;

/** Styles owned by the picker surface; shared UI primitives keep their own styles. */
export const styles = StyleSheet.create({
  pickingLabel: {
      color: colors.accent,
      fontFamily: fontFamily.semibold,
      fontSize: minBodyFontSize.phone,
      letterSpacing: letterSpacing.label,
      marginRight: -letterSpacing.label,
      textAlign: 'center',
    },
  pickerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'stretch',
      justifyContent: 'space-between',
      gap: 12,
    },
  pickedPosition: {
      color: colors.ink,
      fontFamily: fontFamily.semibold,
      fontSize: 26,
    },
  aside: {
      alignSelf: 'stretch',
      color: colors.mutedText,
      fontFamily: fontFamily.medium,
      fontSize: 15,
    },
  asideCentred: {
      textAlign: 'center',
    },
  field: {
      alignItems: 'center',
      alignSelf: 'stretch',
      gap: 10,
    },
  pickerFooter: {
      alignSelf: 'stretch',
      gap: 16,
      marginTop: 'auto',
    },
  failure: {
      alignSelf: 'stretch',
      color: colors.accent,
      fontFamily: fontFamily.medium,
      fontSize: 15,
      lineHeight: 20,
    },
  settingsScreenContent: {
      justifyContent: 'flex-start',
      gap: 10,
      paddingVertical: 16,
    },
  settingsScreenHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'stretch',
      justifyContent: 'space-between',
    },
  settingsHeaderBalance: {
      width: 56,
    },
  settingsScreenTitle: {
      alignSelf: 'stretch',
      color: colors.ink,
      fontFamily: fontFamily.semibold,
      fontSize: 23,
      lineHeight: 28,
    },
  joiningNotice: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'stretch',
      gap: 12,
      paddingHorizontal: 16,
      paddingVertical: 10,
      backgroundColor: colors.onlineSurface,
      borderRadius: radius.row,
    },
  selectedGameSummary: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'stretch',
      gap: 14,
      padding: 11,
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderWidth: borderWidth.hairline,
      borderRadius: radius.row,
    },
  selectedGameArt: {
      width: 82,
      height: 82,
      overflow: 'hidden',
      borderRadius: radius.row,
    },
  selectedGameCopy: {
      flex: 1,
      gap: 5,
    },
  selectedGameTitle: {
      color: colors.ink,
      fontFamily: fontFamily.semibold,
      fontSize: 20,
    },
  selectedGameMeta: {
      color: colors.mutedText,
      fontFamily: fontFamily.medium,
      fontSize: 13,
      lineHeight: 18,
    },
  selectedGameFacts: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
    },
  selectedGameFact: {
      paddingHorizontal: 8,
      paddingVertical: 5,
      gap: 4,
    },
  changeGameAction: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'flex-start',
      gap: 2,
      paddingVertical: 4,
    },
  changeGameText: {
      color: colors.accent,
      fontFamily: fontFamily.semibold,
      fontSize: 15,
    },
  presetGroup: {
      alignSelf: 'stretch',
      gap: 12,
    },
  presetSummary: {
      alignSelf: 'stretch',
      gap: 10,
      paddingHorizontal: 16,
      paddingVertical: 13,
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderWidth: borderWidth.hairline,
      borderRadius: radius.row,
    },
  presetRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
    },
  presetValue: {
      flex: 1,
      color: colors.ink,
      fontFamily: fontFamily.medium,
      fontSize: 15,
    },
  customizeSettings: {
      alignSelf: 'center',
      paddingHorizontal: 16,
      paddingVertical: 6,
    },
  customizeSettingsText: {
      color: colors.accent,
      fontFamily: fontFamily.semibold,
      fontSize: 16,
    },
  stretch: {
      alignSelf: 'stretch',
    },
  gameCard: {
      width: '100%',
      maxWidth: 338,
      alignSelf: 'center',
      borderRadius: radius.card,
      overflow: 'hidden',
    },
  gameCardArt: {
      height: 279,
      alignSelf: 'stretch',
      overflow: 'hidden',
    },
  gameCardPlaceholder: {
      alignSelf: 'center',
      paddingHorizontal: 12,
      paddingVertical: 7,
      backgroundColor: colors.ink,
      borderRadius: radius.chip,
      opacity: 0.9,
    },
  gameCardPlaceholderText: {
      color: colors.inverse,
      fontFamily: fontFamily.semibold,
      fontSize: 12,
      letterSpacing: 1,
    },
  gameCardFooter: {
      alignItems: 'center',
      gap: 12,
      paddingHorizontal: 18,
      paddingVertical: 18,
      borderBottomLeftRadius: radius.card,
      borderBottomRightRadius: radius.card,
    },
  gameCardTitle: {
      color: colors.inverse,
      fontFamily: fontFamily.bold,
      fontSize: 30,
      lineHeight: 36,
      textAlign: 'center',
    },
  gameCardChips: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'center',
      gap: 8,
    },
  gameCardChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: radius.chip,
    },
  gameCardChipWash: {
      backgroundColor: colors.inverse,
      borderRadius: radius.chip,
      opacity: opacity.chipOnArt,
    },
  gameCardChipText: {
      color: colors.inverse,
      fontFamily: fontFamily.medium,
      fontSize: 13,
    },
  modeTabs: {
      flexDirection: 'row',
      alignSelf: 'stretch',
      gap: 10,
    },
  modeTabPressable: {
      flex: 1,
    },
  settingsPanel: {
      alignSelf: 'stretch',
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderWidth: borderWidth.hairline,
      borderRadius: radius.row,
      overflow: 'hidden',
    },
  settingRow: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'stretch',
      justifyContent: 'space-between',
      gap: 12,
      minHeight: 50,
      paddingHorizontal: 12,
      paddingVertical: 5,
    },
  settingRowRuled: {
      borderTopColor: colors.border,
      borderTopWidth: borderWidth.hairline,
    },
  settingLabel: {
      width: 112,
      flexShrink: 0,
      color: colors.ink,
      fontFamily: fontFamily.semibold,
      fontSize: 13,
    },
  collapsedSetting: {
      flex: 1,
      alignItems: 'flex-end',
      gap: 10,
    },
  collapsedSettingButton: {
      minWidth: 0,
      minHeight: 0,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: 0,
      borderWidth: 0,
      borderRadius: 0,
      backgroundColor: 'transparent',
    },
  roundButton: {
      width: 56,
      height: 56,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.surface,
      borderColor: colors.ink,
      borderWidth: borderWidth.hairline,
      borderRadius: radius.pill,
    },
  buttonUnavailable: {
      opacity: opacity.unavailable,
    },
  button: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'stretch',
      justifyContent: 'center',
      // The gap a button with an icon needs, and nothing on one without: an empty
      // flex gap costs a button with a single label nothing.
      gap: 10,
      minHeight: 56,
      backgroundColor: colors.accent,
      borderColor: colors.accent,
      borderWidth: 0,
      borderRadius: radius.button,
    },
  buttonPressed: {
      transform: [{ translateX: PRESS_TRAVEL }, { translateY: PRESS_TRAVEL }],
    },
  buttonLabel: {
      color: colors.surface,
      fontFamily: fontFamily.semibold,
      fontSize: 18,
    },
  waitingFor: {
      alignSelf: 'stretch',
      color: colors.mutedText,
      fontFamily: fontFamily.medium,
      fontSize: 15,
      lineHeight: 20,
    }
});
