import { borderWidth, colors, fontFamily, minBodyFontSize, radius } from '@huddle/ui';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 34, paddingVertical: 28 },
  setupLeft: { width: 700, gap: 14 },
  setupTitle: { color: colors.setupText, fontFamily: fontFamily.bold, fontSize: 74, lineHeight: 82, marginTop: 20 },
  setupMode: { alignSelf: 'flex-start', paddingHorizontal: 16, paddingVertical: 8, borderColor: colors.setupGold, borderWidth: borderWidth.hairline, borderRadius: radius.pill },
  setupModeText: { color: colors.setupGold, fontFamily: fontFamily.semibold, fontSize: 22 },
  setupSummary: { width: 580, marginTop: 12, paddingVertical: 14, borderTopColor: colors.setupMuted, borderBottomColor: colors.setupMuted, borderTopWidth: borderWidth.hairline, borderBottomWidth: borderWidth.hairline, gap: 10, opacity: 0.9 },
  setupSummaryRow: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  setupSummaryCopy: { flex: 1, flexDirection: 'row', justifyContent: 'space-between', gap: 24 },
  setupSummaryLabel: { color: colors.setupMuted, fontFamily: fontFamily.medium, fontSize: 20 },
  setupSummaryValue: { color: colors.setupText, fontFamily: fontFamily.semibold, fontSize: 20, maxWidth: 340, textAlign: 'right' },
  setupHostLineText: { color: colors.setupText, fontFamily: fontFamily.medium, fontSize: 20, marginTop: 14 },
  setupJoinedBlock: { marginTop: 4 },
  setupJoinedLine: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  setupJoinedText: { color: colors.setupText, fontFamily: fontFamily.medium, fontSize: 22 },
  setupJoinedCount: { color: colors.setupGold, fontFamily: fontFamily.bold },
  setupRoster: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 10, marginTop: 10, maxWidth: 560 },
  setupRosterMore: { width: 48, height: 48, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.setupWash, borderColor: colors.setupMuted, borderWidth: borderWidth.hairline, borderRadius: radius.pill },
  setupRosterMoreText: { color: colors.setupText, fontFamily: fontFamily.semibold, fontSize: 18 },
  setupRight: { width: 340, alignItems: 'center', justifyContent: 'center', gap: 18, marginRight: 20 },
  setupRightText: { color: colors.setupText, fontFamily: fontFamily.medium, fontSize: 20, lineHeight: 26, textAlign: 'center' },
  joinCard: { width: 300, alignItems: 'center', gap: 14, padding: 22, backgroundColor: colors.setupSurface, borderRadius: radius.card },
  joinCardEyebrow: { color: colors.ink, fontFamily: fontFamily.semibold, fontSize: minBodyFontSize.tv, letterSpacing: 2, textAlign: 'center' },
  setupCodeRow: { flexDirection: 'row', gap: 8 },
  setupCodeBox: { width: 42, height: 46, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.inverse, borderColor: colors.border, borderWidth: borderWidth.hairline, borderRadius: radius.chip },
  setupCodeBoxText: { color: colors.ink, fontFamily: fontFamily.bold, fontSize: 28, letterSpacing: 2 },
  joinPill: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 16, paddingVertical: 10, backgroundColor: colors.setupWash, borderColor: colors.setupMuted, borderWidth: borderWidth.hairline, borderRadius: radius.pill },
  joinPillText: { color: colors.setupText, fontFamily: fontFamily.medium, fontSize: minBodyFontSize.tv },
});
